# Generated by Django 4.2.8 on 2023-12-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Itens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pat_sn", models.IntegerField(unique=True)),
                ("modelo", models.CharField(max_length=45)),
                ("fabricante", models.CharField(max_length=45)),
                ("descricao", models.CharField(max_length=256)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeraDocumentos.itemcategoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servidores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.IntegerField(unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Transferencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assinado", models.PositiveSmallIntegerField()),
                ("arquivo_endereco", models.CharField(max_length=250)),
                ("tipo", models.TextField()),
                ("prazo", models.DateField()),
                ("motivo", models.CharField(max_length=256)),
                ("data", models.DateTimeField()),
                (
                    "mat_destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinatario",
                        to="GeraDocumentos.servidores",
                    ),
                ),
                (
                    "mat_remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remetente",
                        to="GeraDocumentos.servidores",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferenciasItens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeraDocumentos.itens",
                    ),
                ),
                (
                    "id_transferencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeraDocumentos.transferencias",
                    ),
                ),
            ],
        ),
    ]
