[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
# primaryColor =

# Background color for the main content area.
backgroundColor = '#FFF'

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = '#2E7BCF'

# Color used for almost all text.
# textColor = '#262730'

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =